language: php

php:
  - 7.1
  - 7.2
  - 7.3

sudo: false

 
script:
  - mkdir -p build
  - ./vendor/bin/parallel-lint src tests
  - cd tests
  - ../vendor/bin/phpunit -c configuration.xml --bootstrap Bootstrap.php src
  - echo todo ../vendor/bin/phpcs src --standard=psr2 -sp

after_script:
  - echo todo ../vendor/bin/php-coveralls
  